name: CI/CD Pipeline - Train & Build Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Pastikan URI ini sesuai dengan repo DAGsHub Anda
  MLFLOW_TRACKING_URI: https://dagshub.com/aaarief/membangun-model.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
  MODEL_NAME: "BankMarketingModel_CI"

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn virtualenv matplotlib seaborn imbalanced-learn

    - name: Debug Directory Structure
      run: |
        echo "Melihat isi root folder:"
        ls -R

    - name: Run MLflow Project (Training)
      run: |
        # PERBAIKAN: Langsung masuk ke MLProject (karena ini repo baru)
        cd MLProject
        
        # Jalankan training langsung dengan python (lebih stabil di CI)
        python modelling.py

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/bank-marketing-model:latest"
        
        echo "Building Docker Image: $IMAGE_TAG"
        
        # Build docker dari model yang baru saja dilatih
        mlflow models build-docker \
          -m "models:/$MODEL_NAME/latest" \
          -n "$IMAGE_TAG" \
          --enable-mlserver
          
        echo "Pushing to Docker Hub..."
        docker push "$IMAGE_TAG"