name: CI/CD Pipeline - Train & Build Docker

on:
  push:
    branches: [ main ]
    paths:
      - 'Workflow-CI/**' # Hanya jalan jika ada perubahan di folder ini
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: https://dagshub.com/aaarief/membangun-model.mlflow
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
  MODEL_NAME: "BankMarketingModel_CI"

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install mlflow dagshub pandas scikit-learn virtualenv

    - name: Run MLflow Project (Training)
      run: |
        cd Workflow-CI/MLProject
        # Menjalankan project. Hasilnya model akan ter-log ke DAGsHub
        mlflow run . --no-conda

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push Docker Image
      run: |
        # Mengambil model terbaru dari Registry (yang baru saja dilatih)
        # Format URI: models:/<NamaModel>/<Stage atau Version>
        # Kita ambil versi 'latest'
        
        IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/bank-marketing-model:latest"
        
        echo "Building Docker Image: $IMAGE_TAG"
        
        # Perintah Advanced: mlflow models build-docker
        mlflow models build-docker \
          -m "models:/$MODEL_NAME/latest" \
          -n "$IMAGE_TAG" \
          --enable-mlserver
          
        echo "Pushing to Docker Hub..."
        docker push "$IMAGE_TAG"
